sudo: required
services:
    - docker

before_install:
    - docker build -t clarksonchang/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true clarksonchang/react-test npm test

after_success:
    - docker build -t clarksonchang/multi-client ./client
    - docker build -t clarksonchang/multi-nginx ./nginx
    - docker build -t clarksonchang/multi-server ./server
    - docker build -t clarksonchang/multi-worker ./worker

    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push clarksonchang/multi-client
    - docker push clarksonchang/multi-nginx
    - docker push clarksonchang/multi-server
    - docker push clarksonchang/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    app: multi-docker
    env: MultiDocker-env
    region: ap-southeast-1
    bucket_name: elasticbeanstalk-ap-southeast-1-301658537930
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
